defaults:
  - agents: ddpm_agent

agent_name: oc_ddpm
log_dir: logs/real_robot_${task_suite}/

train_data_path: /media/alr_admin/ECB69036B69002EE/Data_less_obs_new_hdf5_downsampled
#train_data_path: /media/alr_admin/Data/atalay/data  # just for dataset init

task_suite: cupStacking  # pickPlacing cupStacking insertion
if_sim: False

# insert wandb here
wandb:
  entity: tcx513887573
  project: praktikum

group: ${task_suite}_${agent_name}

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

seed: 42

# Network
hidden_dim: 128
num_hidden_layers: 6

# transformer
n_layer: 4
n_head: 4
n_embd: 72

diff_steps: 8

encoder_n_layer: 4
decoder_n_layer: 4

# mamba parameters
n_layer_decoder: 6
n_layer_encoder: 10
n_layers: 10
d_conv: 2

# mamba_ssm_config:
mamba_ssm_cfg:
  d_state: 16
  d_conv: 4
  expand: 2
  dt_rank: "auto"
  dt_min: 0.001
  dt_max: 0.1
  dt_init: "random"
  dt_scale: 1.0
  dt_init_floor: 1e-4
  conv_bias: True
  bias: False
  use_fast_path: True

mamba_encoder_cfg:
  d_state: 16
  d_conv: ${d_conv}
  expand: 2
  dt_rank: "auto"
  dt_min: 0.001
  dt_max: 0.1
  dt_init: "random"
  dt_scale: 1.0
  dt_init_floor: 1e-4
  conv_bias: True
  bias: False
  use_fast_path: True

mamba_decoder_cfg:
  d_state: 16
  d_conv: ${d_conv}
  expand: 2
  dt_rank: "auto"
  dt_min: 0.001
  dt_max: 0.1
  dt_init: "random"
  dt_scale: 1.0
  dt_init_floor: 1e-4
  conv_bias: True
  bias: False
  use_fast_path: True

# Training
train_batch_size: 64
val_batch_size: 256
num_workers: 1
device: 'cuda'
epoch: 100
eval_every_n_epochs: 10
scale_data: True

# Environment
obs_dim: 10 # not used
action_dim: 8
max_len_data: 350

action_seq_size: 5
obs_seq_len: 1

window_size: ${add:${obs_seq},4}
obs_seq: 1
train_action_seq: 5
inference_action_seq: ${train_action_seq}

cam_num: 2
obj_centric: 0
to_tensor: True

# Dataset
trainset:
  # _target_: environments.dataset.real_robot_dataset.Real_Robot_Dataset
  # _target_: environments.dataset.partial_loading_dataset.Partial_Loading_Dataset
  _target_: environments.dataset.lazy_loading_dataset.Lazy_Loading_Dataset
  # _target_: environments.dataset.hdf5_dataset.Hdf5_Dataset
  data_directory: ${train_data_path}
  task_suite: ${task_suite}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  if_sim: ${if_sim}
  cam_0_w: 256
  cam_0_h: 256
  cam_1_w: 256
  cam_1_h: 256
  cam_num: ${cam_num}
  to_tensor: ${to_tensor}
  pre_load_num: 20
  preemptive: False
  feature: 'masked_imgs.hdf5'
  # feature: 'joint_mask.hdf5'
  # feature: 'joint_box.hdf5'
  # feature: 'box.hdf5'
  # feature: 'mask.hdf5'

valset:
  # _target_: environments.dataset.partial_loading_dataset.Partial_Loading_Dataset
  _target_: environments.dataset.lazy_loading_dataset.Lazy_Loading_Dataset
  data_directory: ${train_data_path}
  task_suite: ${task_suite}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  if_sim: ${if_sim}
  cam_0_w: 256
  cam_0_h: 256
  cam_1_w: 256
  cam_1_h: 256
  cam_num: ${cam_num}
  to_tensor: ${to_tensor}
  pre_load_num: 20
  preemptive: False
  # feature: 'joint_mask.hdf5'
  # feature: 'joint_box.hdf5'
  # feature: 'box.hdf5'
  # feature: 'mask.hdf5'
  feature: 'masked_imgs.hdf5'




# Simulation
simulation:
  _target_: simulation.real_robot.RealRobot
  device: ${device}
  resizes: [[256, 256], [256, 256]]
  crops: [[0,-70, 0,null],[0,null, 0,null]]
  crop_resizes: [[256, 256], [256, 256]]

